### ISSUE TITLE
Create error handling for bad logins or duplicate accounts

### ISSUE THREAD

**Issue by stroups91** [galica9999/6845-project#15]
There is code that returns an error if the user provides a bad username or password or tries to create a new account whose username already exists.  We need to add code that displays the error message on the screen.

**Comment by sithlord99us** [comment]
Here is my site I used from a previous exercise.  It notifies if the password is invalid.  It also prevents duplicate accounts to be created.  I've attached my files:
https://pigeon-hearted-leve.000webhostapp.com/ 
[UserComments.zip](https://github.com/galica9999/6845-project/files/7584389/UserComments.zip)

**Comment by sithlord99us** [comment]
Please let me know if you are able to get the files or if you need anything else.
