### ISSUE TITLE
Background visibility and size issues

### ISSUE THREAD

**Issue by stroups91** [galica9999/6845-project#6]
The background has been implemented but the size is over a meg and the image is so busy that its hard to view certain text on the screen.

**Comment by stroups91** [comment]
Should we use a different image or use a image as a header but leave the body blank?

**Comment by technicalnoodles** [comment]
I changed the header to make it so the image is no longer on top of the navbar.  its now below it and it has an overlay to make the image darker.  much easier to read over now.  but the font colors should be updated.  

![image](https://user-images.githubusercontent.com/10239022/142055145-8822071b-8ca9-4331-affd-bc064da54210.png)
