### ISSUE TITLE
New accounts can't register

### ISSUE THREAD

**Issue by stroups91** [galica9999/6845-project#9]
When creating a new account, the first time the task view page loads, the user is unable to register/unregister.  If they log out and log in, they can register/unregister.

**Comment by technicalnoodles** [comment]
we could add a timer on the redirect so that there is time for the db to populate and allow these actions

**Comment by stroups91** [comment]
Good idea Ryan.  I think you're right that its a timing issue.  It didn't seem to do that on my local copy.
